Modify create_updated_flutter_deps script to create a monorepo DEPS
flutter/buildroot pull request #567
Opened 2022-04-29 15:18 UTC by whesse

The script used to roll changes in Dart's third-party dependency version pins to Flutter engine is given a command-line
option to create a new, modified DEPS file.

This DEPS file is used by a gclient solution that can check out specified versions of Dart, engine, and framework in the same
gclient solution.  This is a prototype of a monorepo that can be used to build and test tip-of-tree Dart and Flutter engine together,
and is hosted at https://dart.googlesource.com/monorepo

2022-04-29 15:58 UTC, zanderso requested changes

2022-04-29 15:58 UTC, zanderso commented on tools/dart/create_updated_flutter_deps.py
> +                      action='store_true',
nit: use indentation consistent with the other `add_argument` calls.

2022-04-29 15:58 UTC, zanderso commented on tools/dart/create_updated_flutter_deps.py
> +        sdk_download = True
nit: This file appears to be using a two space indent.

2022-04-29 15:58 UTC, zanderso commented on tools/dart/create_updated_flutter_deps.py
> +        pinned_monorepo_deps = True
ditto

2022-04-29 15:58 UTC, zanderso commented on tools/dart/create_updated_flutter_deps.py
> +      updated_dependencies ):
nit: extra space after `updated_dependencies`.

2022-04-29 15:58 UTC, zanderso commented on tools/dart/create_updated_flutter_deps.py
> +           and i < len(lines) - 3
nit: inconsistent indentation.

2022-05-02 08:31 UTC, whesse commented
Based on review comments, I will take a different direction with this.
The changes to make the monorepo DEPS will be performed by a different script, that will run after the create_updated_flutter_deps script (which will not be modified)

The prototype script here will be copied to the monorepo directory, and used there.

2022-05-02 08:31 UTC, closed without merging