Optimize Wasm for speed instead of size
flutter/buildroot pull request #699
Opened 2023-03-26 22:11 UTC by jason-simmons

This matches Skia's compile flags for building CanvasKit releases.

See https://github.com/flutter/flutter/issues/123484

2023-03-27 00:12 UTC, yjbanov approved these changes
![lgtm](https://user-images.githubusercontent.com/211513/32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d.png)

2023-03-27 00:13 UTC, yjbanov commented
Thanks!

2023-03-27 00:21 UTC, eyebrowsoffire requested changes
Do we actually want to do this? What is the binary size difference? What is the runtime performance difference? Have we done any profiling to see if there are particular spots that are slower at -Oz? On the web, binary size is arguable the most important metric. I don't want to use -O3 just because that's what we've done in the past, we should do a real analysis on this.

2023-03-27 19:47 UTC, kevmoo requested changes
Let's wait on this. See internal discussion.

2023-03-27 20:27 UTC, yjbanov commented
Since this is an easy change, the plan is to try to make `-Oz` work without regressions (at least enough to call the size trade-off a good choice), and if we fail at that, then switch to `-O3`.

2023-03-28 22:46 UTC, eyebrowsoffire approved these changes
Fine with landing this for now until we have a better plan.

2023-03-29 00:42 UTC, merged